# Generated by Django 5.1.6 on 2025-04-04 11:39

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website_name', models.CharField(max_length=30)),
                ('developer_first_name', models.CharField()),
                ('developer_last_name', models.CharField()),
                ('address', models.CharField(max_length=150)),
                ('google_map', models.TextField()),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, unique=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True, unique=True)),
                ('facebook', models.CharField()),
                ('linkedin', models.CharField()),
                ('instagram', models.CharField()),
                ('x', models.TextField()),
            ],
            options={
                'verbose_name': 'NewsNow',
                'verbose_name_plural': 'NewsNow',
                'db_table': 'website_information',
                'ordering': ['website_name'],
                'managed': True,
            },
        ),
    ]
