# Generated by Django 5.1.6 on 2025-04-04 11:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField()),
                ('category_image', models.ImageField(blank=True, default='media/images/news_category_images/no_image.jpg', null=True, upload_to='media/images/news_category_images/')),
            ],
            options={
                'verbose_name': 'News categories',
                'verbose_name_plural': 'News categories',
                'db_table': 'news_categories',
                'ordering': ['id'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_creation', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_of_last_update', models.DateTimeField(default=django.utils.timezone.now)),
                ('title', models.CharField()),
                ('image', models.ImageField(blank=True, default='media/images/profile_images/no_image.jpg', null=True, upload_to='media/images/news_images/')),
                ('text', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news_info', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news_info', to='news.newscategory')),
            ],
            options={
                'verbose_name': 'News',
                'verbose_name_plural': 'News',
                'db_table': 'news',
                'ordering': ['date_of_creation'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='FavoriteNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_saving', models.DateTimeField(default=django.utils.timezone.now)),
                ('reader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_news_info', to=settings.AUTH_USER_MODEL)),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_news_info', to='news.news')),
            ],
            options={
                'verbose_name': 'Favorite news',
                'verbose_name_plural': 'Favorite news',
                'db_table': 'favorite_news',
                'ordering': ['date_of_saving'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_creation', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_of_last_update', models.DateTimeField(default=django.utils.timezone.now)),
                ('rating', models.CharField(choices=[('★★★★★', '★★★★★'), ('★★★★', '★★★★'), ('★★★', '★★★'), ('★★', '★★'), ('★', '★')], default='★', max_length=5)),
                ('comment_text', models.TextField()),
                ('reader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reader_comments_info', to=settings.AUTH_USER_MODEL)),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reader_comments_info', to='news.news')),
            ],
            options={
                'verbose_name': 'Comments',
                'verbose_name_plural': 'Comments',
                'db_table': 'comments',
                'ordering': ['date_of_creation'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_creation', models.DateTimeField(default=django.utils.timezone.now)),
                ('like_or_dislike', models.CharField(choices=[('Like', 'Like'), ('Dislike', 'Dislike')], default='Like', max_length=10)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reader_reactions_info', to='news.comment')),
                ('reader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reader_reactions_info', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reactions',
                'verbose_name_plural': 'Reactions',
                'db_table': 'reactions',
                'ordering': ['date_of_creation'],
                'managed': True,
            },
        ),
    ]
